- name: Copy Zookeeper
  become: yes
  copy:
    src: "apps_repo/{{zk_repo_file}}"
    dest: "{{bd_app_dir}}/{{zk_repo_file}}"
  register: copyzk

- name: Create Zookeeper directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{bd_user}}"
  with_items:
    - "{{ zk_install_dir }}"
    - "{{ zk_data_dir }}"
    - "{{ zk_logs_dir }}"

- name: Extract Zookeeper
  unarchive:
    src: "{{bd_app_dir}}/{{zk_repo_file}}"
    dest: "{{ zk_install_dir }}/"
    remote_src: yes
    extra_opts:
    - --strip-components=1
  when: copyzk.changed

- name: Create Zookeeper Id file
  copy:
    dest: "{{ zk_data_dir }}/myid"
    content: "{{ id }}"

- name: Copy Zookeeper config files
  template:
    src: "{{item}}.j2"
    dest: "{{zk_install_dir}}/conf/{{item}}"
  with_items:
    - "zoo.cfg"
    - "zookeeper-env.sh"

- name: Copy Zookeeper start scripts
  template:
    src: "zookeeper-systemd.j2"
    dest: /etc/systemd/system/zookeeper.service
    owner: root
    group: root
  become: yes

- name: Start Zookeeper service
  systemd:
    daemon_reload: yes
    state: restarted
    name: zookeeper
  become: yes