- name: Copy Zookeeper
  become: yes
  copy:
    src: "apps_repo/{{zk_repo_file}}"
    dest: "{{bd_app_dir}}/{{zk_repo_file}}"

- name: Create Zookeeper install directory
  file:
    path: "{{ zk_install_dir }}"
    state: directory
    owner: "{{bd_user}}"

- name: Create Zookeeper work directory
  file:
    path: "{{ zk_data_dir }}"
    state: directory
    owner: "{{bd_user}}"

- name: Extract Zookeeper
  unarchive:
    src: "{{bd_app_dir}}/{{zk_repo_file}}"
    dest: "{{ zk_install_dir }}/"
    remote_src: yes
    extra_opts:
    - --strip-components=1

- name: Create Zookeeper Id file
  copy:
    dest: "{{ zk_data_dir }}/myid"
    content: "{{ id }}"

- name: Copy Zookeeper config
  template:
    src: "zoo.cfg.j2"
    dest: "{{zk_install_dir}}/conf/zoo.cfg"

- name: Copy Zookeeper start scripts
  template:
    src: "zookeeper-systemd.j2"
    dest: /etc/systemd/system/zookeeper.service
    owner: root
    group: root
  become: yes

- name: Start Zookeeper service
  systemd:
    daemon_reload: yes
    state: started
    name: zookeeper
  become: yes