# Allocation of roles to groups
#   These define which roles each group will deploy
#   Hosts are assigned to groups in the inventory file

- hosts: all
  tasks:
  - include_role:
      name: common

- hosts: zookeepers
  tasks:
  - include_role:
      name: zookeeper

- hosts: kafkas
  tasks:
  - include_role:
      name: kafka

- hosts: storm-supervisors:storm-nimbuses
  tasks:
  - include_role:
      name: storm

- hosts: elastics
  tasks:
  - include_role:
      name: elastic
